services:
  pzserver:
    image: skytuna/zomboid
    container_name: pzserver
    tty: true
    stdin_open: true
    environment:
      # Modify below to configure the server initialization.
      SERVER_NAME: "servertest"
      ADMIN_PASSWORD: "admin"
    ports:
      - "16261:16261/udp"
      - "16262:16262/udp"
    volumes:
      - ./settings:/root/Zomboid/Server
      # Uncomment the line below after creating the new JSON file.
      # - ./ProjectZomboid64.json:/pzserver/ProjectZomboid64.json
      # - ./ProjectZomboid32.json:/pzserver/ProjectZomboid32.json
    restart: unless-stopped
    command: [ "bash", "/pzserver/start-server-with-param.sh" ]
